name: Sync

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:4444w/WebStack-Hugo.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:xn--6mq508o/www.git

    - name: Deploy
      uses: kw214/gitee-pages@v1
      with:
          external_repository: kw214/gitee-pages
          personal_token: ${{ secrets.GITEE_TOKEN }}
          publish_branch: gh-pages
          #publish_dir: ./public
          # allow_empty_commit: true
          # keep_files: true
          # force_orphan: true
          user_name: 'xn--6mq508o'
          user_email: '920578506@qq.com'
          # commit_message: ${{ github.event.head_commit.message }}
          #cname: 'gitee-pages.kimmy.me'